#ifndef _SQLITE_CONFIG_H
#define _SQLITE_CONFIG_H

/* #undef SQLITE_32BIT_ROWID */
/* #undef SQLITE_4_BYTE_ALIGNED_MALLOC */
/* #undef SQLITE_CASE_SENSITIVE_LIKE */
/* #undef SQLITE_CHECK_PAGES */
/* #undef SQLITE_COVERAGE_TEST */
/* #undef SQLITE_DEBUG */
/* #undef SQLITE_DEFAULT_LOCKING_MODE */
/* #undef SQLITE_DISABLE_DIRSYNC */
/* #undef SQLITE_DISABLE_LFS */
/* #undef SQLITE_ENABLE_8_3_NAMES */
/* #undef SQLITE_ENABLE_ATOMIC_WRITE */
/* #undef SQLITE_ENABLE_CEROD */
#define SQLITE_ENABLE_COLUMN_METADATA 1
/* #undef SQLITE_ENABLE_COMMENTS */
/* #undef SQLITE_ENABLE_EXPENSIVE_ASSERT */
/* #undef SQLITE_ENABLE_EXPLAIN_COMMENTS */
/* #undef SQLITE_ENABLE_FTS1 */
/* #undef SQLITE_ENABLE_FTS2 */
/* #undef SQLITE_ENABLE_FTS3 */
/* #undef SQLITE_ENABLE_FTS3_PARENTHESIS */
/* #undef SQLITE_ENABLE_FTS4 */
/* #undef SQLITE_ENABLE_FTS4_UNICODE61 */
/* #undef SQLITE_ENABLE_ICU */
/* #undef SQLITE_ENABLE_IOTRACE */
/* #undef SQLITE_ENABLE_LOAD_EXTENSION */
/* #undef SQLITE_ENABLE_LOCKING_STYLE */
/* #undef SQLITE_ENABLE_MEMORY_MANAGEMENT */
/* #undef SQLITE_ENABLE_MEMSYS3 */
/* #undef SQLITE_ENABLE_MEMSYS5 */
/* #undef SQLITE_ENABLE_MODULE_COMMENTS */
/* #undef SQLITE_ENABLE_OVERSIZE_CELL_CHECK */
#define SQLITE_ENABLE_RTREE 1
/* #undef SQLITE_ENABLE_SQLLOG */
/* #undef SQLITE_ENABLE_STAT2 */
/* #undef SQLITE_ENABLE_STAT3 */
/* #undef SQLITE_ENABLE_STAT3_OR_STAT4 */
/* #undef SQLITE_ENABLE_STAT4 */
/* #undef SQLITE_ENABLE_TREE_EXPLAIN */
/* #undef SQLITE_ENABLE_UNLOCK_NOTIFY */
/* #undef SQLITE_ENABLE_UPDATE_DELETE_LIMIT */
/* #undef SQLITE_ENABLE_WHERETRACE */
/* #undef SQLITE_ENABLE_ZIPVFS */
/* #undef SQLITE_HAS_CODEC */
/* #undef SQLITE_HAVE_ISNAN */
/* #undef SQLITE_HOMEGROWN_RECURSIVE_MUTEX */
/* #undef SQLITE_IGNORE_AFP_LOCK_ERRORS */
/* #undef SQLITE_IGNORE_FLOCK_LOCK_ERRORS */
/* #undef SQLITE_INT64_TYPE */
/* #undef SQLITE_LOCK_TRACE */
/* #undef SQLITE_MAX_SCHEMA_RETRY */
/* #undef SQLITE_MEMDEBUG */
/* #undef SQLITE_MIXED_ENDIAN_64BIT_FLOAT */
/* #undef SQLITE_NO_SYNC */
/* #undef SQLITE_OMIT_ALTERTABLE */
/* #undef SQLITE_OMIT_ANALYZE */
/* #undef SQLITE_OMIT_ATTACH */
/* #undef SQLITE_OMIT_AUTHORIZATION */
/* #undef SQLITE_OMIT_AUTOINCREMENT */
/* #undef SQLITE_OMIT_AUTOINIT */
/* #undef SQLITE_OMIT_AUTOMATIC_INDEX */
/* #undef SQLITE_OMIT_AUTORESET */
/* #undef SQLITE_OMIT_AUTOVACUUM */
/* #undef SQLITE_OMIT_BETWEEN_OPTIMIZATION */
/* #undef SQLITE_OMIT_BLOB_LITERAL */
/* #undef SQLITE_OMIT_BTREECOUNT */
/* #undef SQLITE_OMIT_BUILTIN_TEST */
/* #undef SQLITE_OMIT_CAST */
/* #undef SQLITE_OMIT_CHECK */
/* #undef SQLITE_OMIT_COMPILEOPTION_DIAGS */
/* #undef SQLITE_OMIT_COMPLETE */
/* #undef SQLITE_OMIT_COMPOUND_SELECT */
/* #undef SQLITE_OMIT_CTE */
/* #undef SQLITE_OMIT_DATETIME_FUNCS */
/* #undef SQLITE_OMIT_DECLTYPE */
/* #undef SQLITE_OMIT_DEPRECATED */
/* #undef SQLITE_OMIT_DISKIO */
/* #undef SQLITE_OMIT_EXPLAIN */
/* #undef SQLITE_OMIT_FLAG_PRAGMAS */
/* #undef SQLITE_OMIT_FLOATING_POINT */
/* #undef SQLITE_OMIT_FOREIGN_KEY */
/* #undef SQLITE_OMIT_GET_TABLE */
/* #undef SQLITE_OMIT_INCRBLOB */
/* #undef SQLITE_OMIT_INTEGRITY_CHECK */
/* #undef SQLITE_OMIT_LIKE_OPTIMIZATION */
/* #undef SQLITE_OMIT_LOAD_EXTENSION */
/* #undef SQLITE_OMIT_LOCALTIME */
/* #undef SQLITE_OMIT_LOOKASIDE */
/* #undef SQLITE_OMIT_MEMORYDB */
/* #undef SQLITE_OMIT_MEMORY_ALLOCATION */
/* #undef SQLITE_OMIT_OR_OPTIMIZATION */
/* #undef SQLITE_OMIT_PAGER_PRAGMAS */
/* #undef SQLITE_OMIT_PRAGMA */
/* #undef SQLITE_OMIT_PROGRESS_CALLBACK */
/* #undef SQLITE_OMIT_QUICKBALANCE */
/* #undef SQLITE_OMIT_REINDEX */
/* #undef SQLITE_OMIT_SCHEMA_PRAGMAS */
/* #undef SQLITE_OMIT_SCHEMA_VERSION_PRAGMAS */
/* #undef SQLITE_OMIT_SHARED_CACHE */
/* #undef SQLITE_OMIT_SHUTDOWN_DIRECTORIES */
/* #undef SQLITE_OMIT_SUBQUERY */
/* #undef SQLITE_OMIT_TCL_VARIABLE */
/* #undef SQLITE_OMIT_TEMPDB */
/* #undef SQLITE_OMIT_TRACE */
/* #undef SQLITE_OMIT_TRIGGER */
/* #undef SQLITE_OMIT_TRUNCATE_OPTIMIZATION */
/* #undef SQLITE_OMIT_UTF16 */
/* #undef SQLITE_OMIT_VACUUM */
/* #undef SQLITE_OMIT_VIEW */
/* #undef SQLITE_OMIT_VIRTUALTABLE */
/* #undef SQLITE_OMIT_WAL */
/* #undef SQLITE_OMIT_WSD */
/* #undef SQLITE_OMIT_XFER_OPT */
/* #undef SQLITE_PERFORMANCE_TRACE */
/* #undef SQLITE_PROXY_DEBUG */
/* #undef SQLITE_RTREE_INT_ONLY */
/* #undef SQLITE_SECURE_DELETE */
/* #undef SQLITE_SMALL_STACK */
/* #undef SQLITE_SOUNDEX */
/* #undef SQLITE_TCL */
#define SQLITE_THREADSAFE 2
/* #undef SQLITE_USE_ALLOCA */
/* #undef SQLITE_ZERO_MALLOC */

#define HAVE_READLINE 0

#define HAVE_STDINT_H
/* #undef HAVE_INTTYPES_H */
/* #undef HAVE_UTIME_H */

/* #undef HAVE_GMTIME_R */
#define HAVE_LOCALTIME_R 0
#define HAVE_POSIX_FALLOCATE 0
#define HAVE_USLEEP 0

#define HAVE_FDATASYNC 0
#define HAVE_STRERROR_R 0

#endif
